version: '3'

services:
  gateway:
    container_name: agora_gateway
    build: gateway/
    env_file: .env
    ports:
      - "5001:5000"
    networks:
      - default
    restart: always
  
  marketplace:
    container_name: agora_marketplace
    build: 
      context: marketplace
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8001:8001"
    networks:
      - default
    restart: always

  postgres:
    container_name: agora_postgres
    image: postgres
    env_file: .env
    volumes:
       - postgres:/data/postgres
    ports:
      - "54321:5432"
    networks:
      - default
    restart: always
  
  rabbitmq:
    container_name: agora_rabbitmq
    image: 'bitnami/rabbitmq:latest'
    env_file: .env
    ports:
      - "15672:15672"
      - "56721:56721"
    networks:
      - default
    restart: always
  
    
networks:
  default:

volumes:
  postgres:
 
