version: '3'

services:
  gateway:
    container_name: agora_gateway
    build: gateway/
    ports:
      - "5051:5000"
    networks:
      - default
    restart: always
  
  marketplace:
    container_name: agora_django
    build: 
      context: AGORA_Django/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - default
    restart: always

  postgres:
    container_name: agora_postgres
    image: postgres
    env_file: .env
    volumes:
       - postgres:/data/postgres
    ports:
      - "54321:5432"
    networks:
      - default
    restart: always
  
  rabbitmq:
    container_name: agora_rabbitmq
    image: 'bitnami/rabbitmq:latest'
    env_file: .env
    ports:
      - "56721:5672"
    networks:
      - default
    restart: always
  
    
networks:
  default:

volumes:
  postgres:
 
